name: Multiple jobs

on:
  workflow_dispatch:
  push:
  

jobs:
  built-with-ubuntu:

    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  jobs_2:
    runs-on: ubuntu-latest
    needs: built-with-ubuntu
    env:
      MY_NAME: "Tanzeeb"
    steps:
      - name: bash-version
        run: echo "::add-mask::$MY_NAME"
        
  built-with-windows:
 
    runs-on: windows-latest 
    needs: built-with-ubuntu
    if: always ()
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
